// Generated by tool/ffigen.dart. Do not edit.
// Platform-independent enum definitions extracted from libgit2.g.dart.

/// Flags controlling the behavior of `apply`.
///
/// When the callback:
/// - returns < 0, the apply process will be aborted.
/// - returns > 0, the hunk will not be applied, but the apply process
/// continues
/// - returns 0, the hunk is applied, and the apply process continues.
enum ApplyFlags {
  /// Don't actually make changes, just test that the patch applies.
  /// This is the equivalent of `git apply --check`.
  check(1);

  final int value;
  const ApplyFlags(this.value);

  static ApplyFlags fromValue(int value) => switch (value) {
    1 => check,
    _ => throw ArgumentError('Unknown value for ApplyFlags: $value'),
  };
}

/// Possible application locations for apply
enum ApplyLocation {
  /// Apply the patch to the workdir, leaving the index untouched.
  /// This is the equivalent of `git apply` with no location argument.
  workdir(0),

  /// Apply the patch to the index, leaving the working directory
  /// untouched.  This is the equivalent of `git apply --cached`.
  index$(1),

  /// Apply the patch to both the working directory and the index.
  /// This is the equivalent of `git apply --index`.
  both(2);

  final int value;
  const ApplyLocation(this.value);

  static ApplyLocation fromValue(int value) => switch (value) {
    0 => workdir,
    1 => index$,
    2 => both,
    _ => throw ArgumentError('Unknown value for ApplyLocation: $value'),
  };
}

/// Possible states for an attribute
enum AttrValue {
  /// < The attribute has been left unspecified
  unspecified(0),

  /// < The attribute has been set
  true$(1),

  /// < The attribute has been unset
  false$(2),

  /// < This attribute has a value
  string(3);

  final int value;
  const AttrValue(this.value);

  static AttrValue fromValue(int value) => switch (value) {
    0 => unspecified,
    1 => true$,
    2 => false$,
    3 => string,
    _ => throw ArgumentError('Unknown value for AttrValue: $value'),
  };
}

/// Flags for indicating option behavior for blame APIs.
enum BlameFlag {
  /// Normal blame, the default
  normal(0),

  /// Track lines that have moved within a file (like `git blame -M`).
  ///
  /// This is not yet implemented and reserved for future use.
  trackCopiesSameFile(1),

  /// Track lines that have moved across files in the same commit
  /// (like `git blame -C`).
  ///
  /// This is not yet implemented and reserved for future use.
  trackCopiesSameCommitMoves(2),

  /// Track lines that have been copied from another file that exists
  /// in the same commit (like `git blame -CC`).  Implies SAME_FILE.
  ///
  /// This is not yet implemented and reserved for future use.
  trackCopiesSameCommitCopies(4),

  /// Track lines that have been copied from another file that exists in
  /// *any* commit (like `git blame -CCC`).  Implies SAME_COMMIT_COPIES.
  ///
  /// This is not yet implemented and reserved for future use.
  trackCopiesAnyCommitCopies(8),

  /// Restrict the search of commits to those reachable following only
  /// the first parents.
  firstParent(16),

  /// Use mailmap file to map author and committer names and email
  /// addresses to canonical real names and email addresses. The
  /// mailmap will be read from the working directory, or HEAD in a
  /// bare repository.
  useMailmap(32),

  /// Ignore whitespace differences
  ignoreWhitespace(64);

  final int value;
  const BlameFlag(this.value);

  static BlameFlag fromValue(int value) => switch (value) {
    0 => normal,
    1 => trackCopiesSameFile,
    2 => trackCopiesSameCommitMoves,
    4 => trackCopiesSameCommitCopies,
    8 => trackCopiesAnyCommitCopies,
    16 => firstParent,
    32 => useMailmap,
    64 => ignoreWhitespace,
    _ => throw ArgumentError('Unknown value for BlameFlag: $value'),
  };
}

/// Flags to control the functionality of `blob_filter`.
///
/// @flags
enum BlobFilterFlag {
  /// When set, filters will not be applied to binary files.
  checkForBinary(1),

  /// When set, filters will not load configuration from the
  /// system-wide `gitattributes` in `/etc` (or system equivalent).
  noSystemAttributes(2),

  /// When set, filters will be loaded from a `.gitattributes` file
  /// in the HEAD commit.
  attributesFromHead(4),

  /// When set, filters will be loaded from a `.gitattributes` file
  /// in the specified commit.
  attributesFromCommit(8);

  final int value;
  const BlobFilterFlag(this.value);

  static BlobFilterFlag fromValue(int value) => switch (value) {
    1 => checkForBinary,
    2 => noSystemAttributes,
    4 => attributesFromHead,
    8 => attributesFromCommit,
    _ => throw ArgumentError('Unknown value for BlobFilterFlag: $value'),
  };
}

/// Basic type of any Git branch.
enum BranchT {
  local(1),
  remote(2),
  all(3);

  final int value;
  const BranchT(this.value);

  static BranchT fromValue(int value) => switch (value) {
    1 => local,
    2 => remote,
    3 => all,
    _ => throw ArgumentError('Unknown value for BranchT: $value'),
  };
}

/// Type of SSH host fingerprint
enum CertSsh {
  /// MD5 is available
  md5(1),

  /// SHA-1 is available
  sha1(2),

  /// SHA-256 is available
  sha256(4),

  /// Raw hostkey is available
  raw(8);

  final int value;
  const CertSsh(this.value);

  static CertSsh fromValue(int value) => switch (value) {
    1 => md5,
    2 => sha1,
    4 => sha256,
    8 => raw,
    _ => throw ArgumentError('Unknown value for CertSsh: $value'),
  };
}

enum CertSshRawType {
  /// The raw key is of an unknown type.
  unknown(0),

  /// The raw key is an RSA key.
  rsa(1),

  /// The raw key is a DSS key.
  dss(2),

  /// The raw key is a ECDSA 256 key.
  keyEcdsa256(3),

  /// The raw key is a ECDSA 384 key.
  keyEcdsa384(4),

  /// The raw key is a ECDSA 521 key.
  keyEcdsa521(5),

  /// The raw key is a ED25519 key.
  keyEd25519(6);

  final int value;
  const CertSshRawType(this.value);

  static CertSshRawType fromValue(int value) => switch (value) {
    0 => unknown,
    1 => rsa,
    2 => dss,
    3 => keyEcdsa256,
    4 => keyEcdsa384,
    5 => keyEcdsa521,
    6 => keyEd25519,
    _ => throw ArgumentError('Unknown value for CertSshRawType: $value'),
  };
}

/// Type of host certificate structure that is passed to the check callback
enum CertT {
  /// No information about the certificate is available. This may
  /// happen when using curl.
  none(0),

  /// The `data` argument to the callback will be a pointer to
  /// the DER-encoded data.
  x509(1),

  /// The `data` argument to the callback will be a pointer to a
  /// `cert_hostkey` structure.
  hostkeyLibssh2(2),

  /// The `data` argument to the callback will be a pointer to a
  /// `strarray` with `name:content` strings containing
  /// information about the certificate. This is used when using
  /// curl.
  strarray(3);

  final int value;
  const CertT(this.value);

  static CertT fromValue(int value) => switch (value) {
    0 => none,
    1 => x509,
    2 => hostkeyLibssh2,
    3 => strarray,
    _ => throw ArgumentError('Unknown value for CertT: $value'),
  };
}

/// Checkout notification flags
///
/// Checkout will invoke an options notification callback (`notify_cb`) for
/// certain cases - you pick which ones via `notify_flags`:
///
/// Returning a non-zero value from this callback will cancel the checkout.
/// The non-zero return value will be propagated back and returned by the
/// checkout_... call.
///
/// Notification callbacks are made prior to modifying any files on disk,
/// so canceling on any notification will still happen prior to any files
/// being modified.
///
/// @flags
enum CheckoutNotify {
  none(0),

  /// Invokes checkout on conflicting paths.
  conflict(1),

  /// Notifies about "dirty" files, i.e. those that do not need an update
  /// but no longer match the baseline.  Core git displays these files when
  /// checkout runs, but won't stop the checkout.
  dirty(2),

  /// Sends notification for any file changed.
  updated(4),

  /// Notifies about untracked files.
  untracked(8),

  /// Notifies about ignored files.
  ignored(16),
  all(65535);

  final int value;
  const CheckoutNotify(this.value);

  static CheckoutNotify fromValue(int value) => switch (value) {
    0 => none,
    1 => conflict,
    2 => dirty,
    4 => updated,
    8 => untracked,
    16 => ignored,
    65535 => all,
    _ => throw ArgumentError('Unknown value for CheckoutNotify: $value'),
  };
}

/// Checkout behavior flags
///
/// In libgit2, checkout is used to update the working directory and index
/// to match a target tree.  Unlike git checkout, it does not move the HEAD
/// commit for you - use `repository_set_head` or the like to do that.
///
/// Checkout looks at (up to) four things: the "target" tree you want to
/// check out, the "baseline" tree of what was checked out previously, the
/// working directory for actual files, and the index for staged changes.
///
/// You give checkout one of two strategies for update:
///
/// - `GIT_CHECKOUT_SAFE` is the default, and similar to git's default,
/// which will make modifications that will not lose changes in the
/// working directory.
///
/// |  target == baseline   |  target != baseline  |
/// ---------------------|-----------------------|----------------------|
/// workdir == baseline |       no action       |  create, update, or  |
/// |                       |     delete file      |
/// ---------------------|-----------------------|----------------------|
/// workdir exists and  |       no action       |   conflict (notify   |
/// is != baseline    | notify dirty MODIFIED | and cancel checkout) |
/// ---------------------|-----------------------|----------------------|
/// workdir missing,   | notify dirty DELETED  |     create file      |
/// baseline present   |                       |                      |
/// ---------------------|-----------------------|----------------------|
///
/// - `GIT_CHECKOUT_FORCE` will take any action to make the working
/// directory match the target (including potentially discarding
/// modified files).
///
/// To emulate `git checkout`, use `GIT_CHECKOUT_SAFE` with a checkout
/// notification callback (see below) that displays information about dirty
/// files.  The default behavior will cancel checkout on conflicts.
///
/// To emulate `git checkout-index`, use `GIT_CHECKOUT_SAFE` with a
/// notification callback that cancels the operation if a dirty-but-existing
/// file is found in the working directory.  This core git command isn't
/// quite "force" but is sensitive about some types of changes.
///
/// To emulate `git checkout -f`, use `GIT_CHECKOUT_FORCE`.
///
///
/// There are some additional flags to modify the behavior of checkout:
///
/// - `GIT_CHECKOUT_DRY_RUN` is a dry-run strategy that checks for conflicts,
/// etc., but doesn't make any actual changes.
///
/// - GIT_CHECKOUT_ALLOW_CONFLICTS makes SAFE mode apply safe file updates
/// even if there are conflicts (instead of cancelling the checkout).
///
/// - GIT_CHECKOUT_REMOVE_UNTRACKED means remove untracked files (i.e. not
/// in target, baseline, or index, and not ignored) from the working dir.
///
/// - GIT_CHECKOUT_REMOVE_IGNORED means remove ignored files (that are also
/// untracked) from the working directory as well.
///
/// - GIT_CHECKOUT_UPDATE_ONLY means to only update the content of files that
/// already exist.  Files will not be created nor deleted.  This just skips
/// applying adds, deletes, and typechanges.
///
/// - GIT_CHECKOUT_DONT_UPDATE_INDEX prevents checkout from writing the
/// updated files' information to the index.
///
/// - Normally, checkout will reload the index and git attributes from disk
/// before any operations.  GIT_CHECKOUT_NO_REFRESH prevents this reload.
///
/// - Unmerged index entries are conflicts.  GIT_CHECKOUT_SKIP_UNMERGED skips
/// files with unmerged index entries instead.  GIT_CHECKOUT_USE_OURS and
/// GIT_CHECKOUT_USE_THEIRS to proceed with the checkout using either the
/// stage 2 ("ours") or stage 3 ("theirs") version of files in the index.
///
/// - GIT_CHECKOUT_DONT_OVERWRITE_IGNORED prevents ignored files from being
/// overwritten.  Normally, files that are ignored in the working directory
/// are not considered "precious" and may be overwritten if the checkout
/// target contains that file.
///
/// - GIT_CHECKOUT_DONT_REMOVE_EXISTING prevents checkout from removing
/// files or folders that fold to the same name on case insensitive
/// filesystems.  This can cause files to retain their existing names
/// and write through existing symbolic links.
///
/// @flags
enum CheckoutStrategy {
  /// Allow safe updates that cannot overwrite uncommitted data.
  /// If the uncommitted changes don't conflict with the checked
  /// out files, the checkout will still proceed, leaving the
  /// changes intact.
  safe(0),

  /// Allow all updates to force working directory to look like
  /// the index, potentially losing data in the process.
  force(2),

  /// Allow checkout to recreate missing files
  recreateMissing(4),

  /// Allow checkout to make safe updates even if conflicts are found
  allowConflicts(16),

  /// Remove untracked files not in index (that are not ignored)
  removeUntracked(32),

  /// Remove ignored files not in index
  removeIgnored(64),

  /// Only update existing files, don't create new ones
  updateOnly(128),

  /// Normally checkout updates index entries as it goes; this stops that.
  /// Implies `GIT_CHECKOUT_DONT_WRITE_INDEX`.
  dontUpdateIndex(256),

  /// Don't refresh index/config/etc before doing checkout
  noRefresh(512),

  /// Allow checkout to skip unmerged files
  skipUnmerged(1024),

  /// For unmerged files, checkout stage 2 from index
  useOurs(2048),

  /// For unmerged files, checkout stage 3 from index
  useTheirs(4096),

  /// Treat pathspec as simple list of exact match file paths
  disablePathspecMatch(8192),

  /// Ignore directories in use, they will be left empty
  skipLockedDirectories(262144),

  /// Don't overwrite ignored files that exist in the checkout target
  dontOverwriteIgnored(524288),

  /// Write normal merge files for conflicts
  conflictStyleMerge(1048576),

  /// Include common ancestor data in diff3 format files for conflicts
  conflictStyleDiff3(2097152),

  /// Don't overwrite existing files or folders
  dontRemoveExisting(4194304),

  /// Normally checkout writes the index upon completion; this prevents that.
  dontWriteIndex(8388608),

  /// Perform a "dry run", reporting what _would_ be done but
  /// without actually making changes in the working directory
  /// or the index.
  dryRun(16777216),

  /// Include common ancestor data in zdiff3 format for conflicts
  conflictStyleZdiff3(33554432),

  /// Do not do a checkout and do not fire callbacks; this is primarily
  /// useful only for internal functions that will perform the
  /// checkout themselves but need to pass checkout options into
  /// another function, for example, `clone`.
  none(1073741824),

  /// Recursively checkout submodules with same options (NOT IMPLEMENTED)
  updateSubmodules(65536),

  /// Recursively checkout submodules if HEAD moved in super repo (NOT IMPLEMENTED)
  updateSubmodulesIfChanged(131072);

  final int value;
  const CheckoutStrategy(this.value);

  static CheckoutStrategy fromValue(int value) => switch (value) {
    0 => safe,
    2 => force,
    4 => recreateMissing,
    16 => allowConflicts,
    32 => removeUntracked,
    64 => removeIgnored,
    128 => updateOnly,
    256 => dontUpdateIndex,
    512 => noRefresh,
    1024 => skipUnmerged,
    2048 => useOurs,
    4096 => useTheirs,
    8192 => disablePathspecMatch,
    262144 => skipLockedDirectories,
    524288 => dontOverwriteIgnored,
    1048576 => conflictStyleMerge,
    2097152 => conflictStyleDiff3,
    4194304 => dontRemoveExisting,
    8388608 => dontWriteIndex,
    16777216 => dryRun,
    33554432 => conflictStyleZdiff3,
    1073741824 => none,
    65536 => updateSubmodules,
    131072 => updateSubmodulesIfChanged,
    _ => throw ArgumentError('Unknown value for CheckoutStrategy: $value'),
  };
}

/// Options for bypassing the git-aware transport on clone. Bypassing
/// it means that instead of a fetch, libgit2 will copy the object
/// database directory instead of figuring out what it needs, which is
/// faster. If possible, it will hardlink the files to save space.
enum CloneLocal {
  /// Auto-detect (default), libgit2 will bypass the git-aware
  /// transport for local paths, but use a normal fetch for
  /// `file://` urls.
  localAuto(0),

  /// Bypass the git-aware transport even for a `file://` url.
  local(1),

  /// Do no bypass the git-aware transport
  noLocal(2),

  /// Bypass the git-aware transport, but do not try to use
  /// hardlinks.
  localNoLinks(3);

  final int value;
  const CloneLocal(this.value);

  static CloneLocal fromValue(int value) => switch (value) {
    0 => localAuto,
    1 => local,
    2 => noLocal,
    3 => localNoLinks,
    _ => throw ArgumentError('Unknown value for CloneLocal: $value'),
  };
}

/// Priority level of a config file.
///
/// These priority levels correspond to the natural escalation logic
/// (from higher to lower) when reading or searching for config entries
/// in git.git. Meaning that for the same key, the configuration in
/// the local configuration is preferred over the configuration in
/// the system configuration file.
///
/// Callers can add their own custom configuration, beginning at the
/// `GIT_CONFIG_LEVEL_APP` level.
///
/// Writes, by default, occur in the highest priority level backend
/// that is writable. This ordering can be overridden with
/// `config_set_writeorder`.
///
/// config_open_default() and git_repository_config() honor those
/// priority levels as well.
///
/// @see config_open_default
/// @see repository_config
enum ConfigLevel {
  /// System-wide on Windows, for compatibility with "Portable Git".
  levelProgramdata(1),

  /// System-wide configuration file; `/etc/gitconfig` on Linux.
  levelSystem(2),

  /// XDG compatible configuration file; typically
  /// `~/.config/git/config`.
  levelXdg(3),

  /// Global configuration file is the user-specific configuration;
  /// typically `~/.gitconfig`.
  levelGlobal(4),

  /// Local configuration, the repository-specific configuration file;
  /// typically `$GIT_DIR/config`.
  levelLocal(5),

  /// Worktree-specific configuration; typically
  /// `$GIT_DIR/config.worktree`.
  levelWorktree(6),

  /// Application-specific configuration file. Callers into libgit2
  /// can add their own configuration beginning at this level.
  levelApp(7),

  /// Not a configuration level; callers can use this value when
  /// querying configuration levels to specify that they want to
  /// have data from the highest-level currently configuration.
  /// This can be used to indicate that callers want the most
  /// specific config file available that actually is loaded.
  highestLevel(-1);

  final int value;
  const ConfigLevel(this.value);

  static ConfigLevel fromValue(int value) => switch (value) {
    1 => levelProgramdata,
    2 => levelSystem,
    3 => levelXdg,
    4 => levelGlobal,
    5 => levelLocal,
    6 => levelWorktree,
    7 => levelApp,
    -1 => highestLevel,
    _ => throw ArgumentError('Unknown value for ConfigLevel: $value'),
  };
}

/// Config var type
enum ConfigmapT {
  false$(0),
  true$(1),
  int32(2),
  string(3);

  final int value;
  const ConfigmapT(this.value);

  static ConfigmapT fromValue(int value) => switch (value) {
    0 => false$,
    1 => true$,
    2 => int32,
    3 => string,
    _ => throw ArgumentError('Unknown value for ConfigmapT: $value'),
  };
}

/// Supported credential types
///
/// This represents the various types of authentication methods supported by
/// the library.
enum CredentialT {
  /// A vanilla user/password request
  /// @see credential_userpass_plaintext_new
  userpassPlaintext(1),

  /// An SSH key-based authentication request
  /// @see credential_ssh_key_new
  sshKey(2),

  /// An SSH key-based authentication request, with a custom signature
  /// @see credential_ssh_custom_new
  sshCustom(4),

  /// An NTLM/Negotiate-based authentication request.
  /// @see credential_default
  default$(8),

  /// An SSH interactive authentication request
  /// @see credential_ssh_interactive_new
  sshInteractive(16),

  /// Username-only authentication request
  ///
  /// Used as a pre-authentication step if the underlying transport
  /// (eg. SSH, with no username in its URL) does not know which username
  /// to use.
  ///
  /// @see credential_username_new
  username(32),

  /// An SSH key-based authentication request
  ///
  /// Allows credentials to be read from memory instead of files.
  /// Note that because of differences in crypto backend support, it might
  /// not be functional.
  ///
  /// @see credential_ssh_key_memory_new
  sshMemory(64);

  final int value;
  const CredentialT(this.value);

  static CredentialT fromValue(int value) => switch (value) {
    1 => userpassPlaintext,
    2 => sshKey,
    4 => sshCustom,
    8 => default$,
    16 => sshInteractive,
    32 => username,
    64 => sshMemory,
    _ => throw ArgumentError('Unknown value for CredentialT: $value'),
  };
}

/// What type of change is described by a diff_delta?
///
/// `GIT_DELTA_RENAMED` and `GIT_DELTA_COPIED` will only show up if you run
/// `diff_find_similar()` on the diff object.
///
/// `GIT_DELTA_TYPECHANGE` only shows up given `GIT_DIFF_INCLUDE_TYPECHANGE`
/// in the option flags (otherwise type changes will be split into ADDED /
/// DELETED pairs).
enum Delta {
  /// < no changes
  unmodified(0),

  /// < entry does not exist in old version
  added(1),

  /// < entry does not exist in new version
  deleted(2),

  /// < entry content changed between old and new
  modified(3),

  /// < entry was renamed between old and new
  renamed(4),

  /// < entry was copied from another old entry
  copied(5),

  /// < entry is ignored item in workdir
  ignored(6),

  /// < entry is untracked item in workdir
  untracked(7),

  /// < type of entry changed between old and new
  typechange(8),

  /// < entry is unreadable
  unreadable(9),

  /// < entry in the index is conflicted
  conflicted(10);

  final int value;
  const Delta(this.value);

  static Delta fromValue(int value) => switch (value) {
    0 => unmodified,
    1 => added,
    2 => deleted,
    3 => modified,
    4 => renamed,
    5 => copied,
    6 => ignored,
    7 => untracked,
    8 => typechange,
    9 => unreadable,
    10 => conflicted,
    _ => throw ArgumentError('Unknown value for Delta: $value'),
  };
}

/// Reference lookup strategy
///
/// These behave like the --tags and --all options to git-describe,
/// namely they say to look for any reference in either refs/tags/ or
/// refs/ respectively.
enum DescribeStrategy {
  default$(0),
  tags(1),
  all(2);

  final int value;
  const DescribeStrategy(this.value);

  static DescribeStrategy fromValue(int value) => switch (value) {
    0 => default$,
    1 => tags,
    2 => all,
    _ => throw ArgumentError('Unknown value for DescribeStrategy: $value'),
  };
}

/// When producing a binary diff, the binary data returned will be
/// either the deflated full ("literal") contents of the file, or
/// the deflated binary delta between the two sides (whichever is
/// smaller).
enum DiffBinaryT {
  /// There is no binary delta.
  none(0),

  /// The binary data is the literal contents of the file.
  literal(1),

  /// The binary data is the delta from one side to the other.
  delta(2);

  final int value;
  const DiffBinaryT(this.value);

  static DiffBinaryT fromValue(int value) => switch (value) {
    0 => none,
    1 => literal,
    2 => delta,
    _ => throw ArgumentError('Unknown value for DiffBinaryT: $value'),
  };
}

/// Flags to control the behavior of diff rename/copy detection.
enum DiffFind {
  /// Obey `diff.renames`. Overridden by any other GIT_DIFF_FIND_... flag.
  findByConfig(0),

  /// Look for renames? (`--find-renames`)
  findRenames(1),

  /// Consider old side of MODIFIED for renames? (`--break-rewrites=N`)
  findRenamesFromRewrites(2),

  /// Look for copies? (a la `--find-copies`).
  findCopies(4),

  /// Consider UNMODIFIED as copy sources? (`--find-copies-harder`).
  ///
  /// For this to work correctly, use GIT_DIFF_INCLUDE_UNMODIFIED when
  /// the initial `diff` is being generated.
  findCopiesFromUnmodified(8),

  /// Mark significant rewrites for split (`--break-rewrites=/M`)
  findRewrites(16),

  /// Actually split large rewrites into delete/add pairs
  breakRewrites(32),

  /// Mark rewrites for split and break into delete/add pairs
  findAndBreakRewrites(48),

  /// Find renames/copies for UNTRACKED items in working directory.
  ///
  /// For this to work correctly, use GIT_DIFF_INCLUDE_UNTRACKED when the
  /// initial `diff` is being generated (and obviously the diff must
  /// be against the working directory for this to make sense).
  findForUntracked(64),

  /// Turn on all finding features.
  findAll(255),

  /// Measure similarity ignoring all whitespace
  findIgnoreWhitespace(4096),

  /// Measure similarity including all data
  findDontIgnoreWhitespace(8192),

  /// Measure similarity only by comparing SHAs (fast and cheap)
  findExactMatchOnly(16384),

  /// Do not break rewrites unless they contribute to a rename.
  ///
  /// Normally, GIT_DIFF_FIND_AND_BREAK_REWRITES will measure the self-
  /// similarity of modified files and split the ones that have changed a
  /// lot into a DELETE / ADD pair.  Then the sides of that pair will be
  /// considered candidates for rename and copy detection.
  ///
  /// If you add this flag in and the split pair is *not* used for an
  /// actual rename or copy, then the modified record will be restored to
  /// a regular MODIFIED record instead of being split.
  breakRewritesForRenamesOnly(32768),

  /// Remove any UNMODIFIED deltas after find_similar is done.
  ///
  /// Using GIT_DIFF_FIND_COPIES_FROM_UNMODIFIED to emulate the
  /// --find-copies-harder behavior requires building a diff with the
  /// GIT_DIFF_INCLUDE_UNMODIFIED flag.  If you do not want UNMODIFIED
  /// records in the final result, pass this flag to have them removed.
  findRemoveUnmodified(65536);

  /// Measure similarity ignoring leading whitespace (default)
  static const findIgnoreLeadingWhitespace = findByConfig;

  final int value;
  const DiffFind(this.value);

  static DiffFind fromValue(int value) => switch (value) {
    0 => findByConfig,
    1 => findRenames,
    2 => findRenamesFromRewrites,
    4 => findCopies,
    8 => findCopiesFromUnmodified,
    16 => findRewrites,
    32 => breakRewrites,
    48 => findAndBreakRewrites,
    64 => findForUntracked,
    255 => findAll,
    4096 => findIgnoreWhitespace,
    8192 => findDontIgnoreWhitespace,
    16384 => findExactMatchOnly,
    32768 => breakRewritesForRenamesOnly,
    65536 => findRemoveUnmodified,
    _ => throw ArgumentError('Unknown value for DiffFind: $value'),
  };

  @override
  String toString() {
    if (this == findByConfig)
      return "DiffFind.findByConfig, DiffFind.findIgnoreLeadingWhitespace";
    return super.toString();
  }
}

/// Flags for the delta object and the file objects on each side.
///
/// These flags are used for both the `flags` value of the `diff_delta`
/// and the flags for the `diff_file` objects representing the old and
/// new sides of the delta.  Values outside of this public range should be
/// considered reserved for internal or future use.
enum DiffFlag {
  /// < file(s) treated as binary data
  binary(1),

  /// < file(s) treated as text data
  notBinary(2),

  /// < `id` value is known correct
  validId(4),

  /// < file exists at this side of the delta
  exists(8),

  /// < file size value is known correct
  validSize(16);

  final int value;
  const DiffFlag(this.value);

  static DiffFlag fromValue(int value) => switch (value) {
    1 => binary,
    2 => notBinary,
    4 => validId,
    8 => exists,
    16 => validSize,
    _ => throw ArgumentError('Unknown value for DiffFlag: $value'),
  };
}

/// Possible output formats for diff data
enum DiffFormat {
  /// < full git diff
  patch(1),

  /// < just the file headers of patch
  patchHeader(2),

  /// < like git diff --raw
  raw(3),

  /// < like git diff --name-only
  nameOnly(4),

  /// < like git diff --name-status
  nameStatus(5),

  /// < git diff as used by git patch-id
  patchId(6);

  final int value;
  const DiffFormat(this.value);

  static DiffFormat fromValue(int value) => switch (value) {
    1 => patch,
    2 => patchHeader,
    3 => raw,
    4 => nameOnly,
    5 => nameStatus,
    6 => patchId,
    _ => throw ArgumentError('Unknown value for DiffFormat: $value'),
  };
}

/// Formatting options for diff e-mail generation
enum DiffFormatEmailFlags {
  /// Normal patch, the default
  none(0),

  /// Don't insert "[PATCH]" in the subject header
  excludeSubjectPatchMarker(1);

  final int value;
  const DiffFormatEmailFlags(this.value);

  static DiffFormatEmailFlags fromValue(int value) => switch (value) {
    0 => none,
    1 => excludeSubjectPatchMarker,
    _ => throw ArgumentError('Unknown value for DiffFormatEmailFlags: $value'),
  };
}

/// Line origin constants.
///
/// These values describe where a line came from and will be passed to
/// the diff_line_cb when iterating over a diff.  There are some
/// special origin constants at the end that are used for the text
/// output callbacks to demarcate lines that are actually part of
/// the file or hunk headers.
enum DiffLineT {
  context(32),
  addition(43),
  deletion(45),

  /// < Both files have no LF at end
  contextEofnl(61),

  /// < Old has no LF at end, new does
  addEofnl(62),

  /// < Old has LF at end, new does not
  delEofnl(60),
  fileHdr(70),
  hunkHdr(72),

  /// < For "Binary files x and y differ"
  binary(66);

  final int value;
  const DiffLineT(this.value);

  static DiffLineT fromValue(int value) => switch (value) {
    32 => context,
    43 => addition,
    45 => deletion,
    61 => contextEofnl,
    62 => addEofnl,
    60 => delEofnl,
    70 => fileHdr,
    72 => hunkHdr,
    66 => binary,
    _ => throw ArgumentError('Unknown value for DiffLineT: $value'),
  };
}

/// Flags for diff options.  A combination of these flags can be passed
/// in via the `flags` value in the `diff_options`.
enum DiffOption {
  /// Normal diff, the default
  normal(0),

  /// Reverse the sides of the diff
  reverse(1),

  /// Include ignored files in the diff
  includeIgnored(2),

  /// Even with GIT_DIFF_INCLUDE_IGNORED, an entire ignored directory
  /// will be marked with only a single entry in the diff; this flag
  /// adds all files under the directory as IGNORED entries, too.
  recurseIgnoredDirs(4),

  /// Include untracked files in the diff
  includeUntracked(8),

  /// Even with GIT_DIFF_INCLUDE_UNTRACKED, an entire untracked
  /// directory will be marked with only a single entry in the diff
  /// (a la what core Git does in `git status`); this flag adds *all*
  /// files under untracked directories as UNTRACKED entries, too.
  recurseUntrackedDirs(16),

  /// Include unmodified files in the diff
  includeUnmodified(32),

  /// Normally, a type change between files will be converted into a
  /// DELETED record for the old and an ADDED record for the new; this
  /// options enabled the generation of TYPECHANGE delta records.
  includeTypechange(64),

  /// Even with GIT_DIFF_INCLUDE_TYPECHANGE, blob->tree changes still
  /// generally show as a DELETED blob.  This flag tries to correctly
  /// label blob->tree transitions as TYPECHANGE records with new_file's
  /// mode set to tree.  Note: the tree SHA will not be available.
  includeTypechangeTrees(128),

  /// Ignore file mode changes
  ignoreFilemode(256),

  /// Treat all submodules as unmodified
  ignoreSubmodules(512),

  /// Use case insensitive filename comparisons
  ignoreCase(1024),

  /// May be combined with `GIT_DIFF_IGNORE_CASE` to specify that a file
  /// that has changed case will be returned as an add/delete pair.
  includeCasechange(2048),

  /// If the pathspec is set in the diff options, this flags indicates
  /// that the paths will be treated as literal paths instead of
  /// fnmatch patterns.  Each path in the list must either be a full
  /// path to a file or a directory.  (A trailing slash indicates that
  /// the path will _only_ match a directory).  If a directory is
  /// specified, all children will be included.
  disablePathspecMatch(4096),

  /// Disable updating of the `binary` flag in delta records.  This is
  /// useful when iterating over a diff if you don't need hunk and data
  /// callbacks and want to avoid having to load file completely.
  skipBinaryCheck(8192),

  /// When diff finds an untracked directory, to match the behavior of
  /// core Git, it scans the contents for IGNORED and UNTRACKED files.
  /// If *all* contents are IGNORED, then the directory is IGNORED; if
  /// any contents are not IGNORED, then the directory is UNTRACKED.
  /// This is extra work that may not matter in many cases.  This flag
  /// turns off that scan and immediately labels an untracked directory
  /// as UNTRACKED (changing the behavior to not match core Git).
  enableFastUntrackedDirs(16384),

  /// When diff finds a file in the working directory with stat
  /// information different from the index, but the OID ends up being the
  /// same, write the correct stat information into the index.  Note:
  /// without this flag, diff will always leave the index untouched.
  updateIndex(32768),

  /// Include unreadable files in the diff
  includeUnreadable(65536),

  /// Include unreadable files in the diff
  includeUnreadableAsUntracked(131072),

  /// Use a heuristic that takes indentation and whitespace into account
  /// which generally can produce better diffs when dealing with ambiguous
  /// diff hunks.
  indentHeuristic(262144),

  /// Ignore blank lines
  ignoreBlankLines(524288),

  /// Treat all files as text, disabling binary attributes & detection
  forceText(1048576),

  /// Treat all files as binary, disabling text diffs
  forceBinary(2097152),

  /// Ignore all whitespace
  ignoreWhitespace(4194304),

  /// Ignore changes in amount of whitespace
  ignoreWhitespaceChange(8388608),

  /// Ignore whitespace at end of line
  ignoreWhitespaceEol(16777216),

  /// When generating patch text, include the content of untracked
  /// files.  This automatically turns on GIT_DIFF_INCLUDE_UNTRACKED but
  /// it does not turn on GIT_DIFF_RECURSE_UNTRACKED_DIRS.  Add that
  /// flag if you want the content of every single UNTRACKED file.
  showUntrackedContent(33554432),

  /// When generating output, include the names of unmodified files if
  /// they are included in the diff.  Normally these are skipped in
  /// the formats that list files (e.g. name-only, name-status, raw).
  /// Even with this, these will not be included in patch format.
  showUnmodified(67108864),

  /// Use the "patience diff" algorithm
  patience(268435456),

  /// Take extra time to find minimal diff
  minimal(536870912),

  /// Include the necessary deflate / delta information so that `git-apply`
  /// can apply given diff information to binary files.
  showBinary(1073741824);

  final int value;
  const DiffOption(this.value);

  static DiffOption fromValue(int value) => switch (value) {
    0 => normal,
    1 => reverse,
    2 => includeIgnored,
    4 => recurseIgnoredDirs,
    8 => includeUntracked,
    16 => recurseUntrackedDirs,
    32 => includeUnmodified,
    64 => includeTypechange,
    128 => includeTypechangeTrees,
    256 => ignoreFilemode,
    512 => ignoreSubmodules,
    1024 => ignoreCase,
    2048 => includeCasechange,
    4096 => disablePathspecMatch,
    8192 => skipBinaryCheck,
    16384 => enableFastUntrackedDirs,
    32768 => updateIndex,
    65536 => includeUnreadable,
    131072 => includeUnreadableAsUntracked,
    262144 => indentHeuristic,
    524288 => ignoreBlankLines,
    1048576 => forceText,
    2097152 => forceBinary,
    4194304 => ignoreWhitespace,
    8388608 => ignoreWhitespaceChange,
    16777216 => ignoreWhitespaceEol,
    33554432 => showUntrackedContent,
    67108864 => showUnmodified,
    268435456 => patience,
    536870912 => minimal,
    1073741824 => showBinary,
    _ => throw ArgumentError('Unknown value for DiffOption: $value'),
  };
}

/// Formatting options for diff stats
enum DiffStatsFormat {
  /// No stats
  none(0),

  /// Full statistics, equivalent of `--stat`
  full(1),

  /// Short statistics, equivalent of `--shortstat`
  short(2),

  /// Number statistics, equivalent of `--numstat`
  number(4),

  /// Extended header information such as creations, renames and mode changes, equivalent of `--summary`
  includeSummary(8);

  final int value;
  const DiffStatsFormat(this.value);

  static DiffStatsFormat fromValue(int value) => switch (value) {
    0 => none,
    1 => full,
    2 => short,
    4 => number,
    8 => includeSummary,
    _ => throw ArgumentError('Unknown value for DiffStatsFormat: $value'),
  };
}

/// Direction of the connection.
///
/// We need this because we need to know whether we should call
/// git-upload-pack or git-receive-pack on the remote end when get_refs
/// gets called.
enum Direction {
  fetch(0),
  push(1);

  final int value;
  const Direction(this.value);

  static Direction fromValue(int value) => switch (value) {
    0 => fetch,
    1 => push,
    _ => throw ArgumentError('Unknown value for Direction: $value'),
  };
}

/// Formatting options for diff e-mail generation
enum EmailCreateFlags {
  /// Normal patch, the default
  default$(0),

  /// Do not include patch numbers in the subject prefix.
  omitNumbers(1),

  /// Include numbers in the subject prefix even when the
  /// patch is for a single commit (1/1).
  alwaysNumber(2),

  /// Do not perform rename or similarity detection.
  noRenames(4);

  final int value;
  const EmailCreateFlags(this.value);

  static EmailCreateFlags fromValue(int value) => switch (value) {
    0 => default$,
    1 => omitNumbers,
    2 => alwaysNumber,
    4 => noRenames,
    _ => throw ArgumentError('Unknown value for EmailCreateFlags: $value'),
  };
}

/// Generic return codes
enum ErrorCode {
  /// No error occurred; the call was successful.
  ok(0),

  /// An error occurred; call `error_last` for more information.
  error(-1),

  /// < Requested object could not be found.
  enotfound(-3),

  /// < Object exists preventing operation.
  eexists(-4),

  /// < More than one object matches.
  eambiguous(-5),

  /// < Output buffer too short to hold data.
  ebufs(-6),

  /// GIT_EUSER is a special error that is never generated by libgit2
  /// code.  You can return it from a callback (e.g to stop an iteration)
  /// to know that it was generated by the callback and not by libgit2.
  euser(-7),

  /// < Operation not allowed on bare repository.
  ebarerepo(-8),

  /// < HEAD refers to branch with no commits.
  eunbornbranch(-9),

  /// < Merge in progress prevented operation
  eunmerged(-10),

  /// < Reference was not fast-forwardable
  enonfastforward(-11),

  /// < Name/ref spec was not in a valid format
  einvalidspec(-12),

  /// < Checkout conflicts prevented operation
  econflict(-13),

  /// < Lock file prevented operation
  elocked(-14),

  /// < Reference value does not match expected
  emodified(-15),

  /// < Authentication error
  eauth(-16),

  /// < Server certificate is invalid
  ecertificate(-17),

  /// < Patch/merge has already been applied
  eapplied(-18),

  /// < The requested peel operation is not possible
  epeel(-19),

  /// < Unexpected EOF
  eeof(-20),

  /// < Invalid operation or input
  einvalid(-21),

  /// < Uncommitted changes in index prevented operation
  euncommitted(-22),

  /// < The operation is not valid for a directory
  edirectory(-23),

  /// < A merge conflict exists and cannot continue
  emergeconflict(-24),

  /// < A user-configured callback refused to act
  passthrough(-30),

  /// < Signals end of iteration with iterator
  iterover(-31),

  /// < Internal only
  retry(-32),

  /// < Hashsum mismatch in object
  emismatch(-33),

  /// < Unsaved changes in the index would be overwritten
  eindexdirty(-34),

  /// < Patch application failed
  eapplyfail(-35),

  /// < The object is not owned by the current user
  eowner(-36),

  /// < The operation timed out
  timeout(-37),

  /// < There were no changes
  eunchanged(-38),

  /// < An option is not supported
  enotsupported(-39),

  /// < The subject is read-only
  ereadonly(-40);

  final int value;
  const ErrorCode(this.value);

  static ErrorCode fromValue(int value) => switch (value) {
    0 => ok,
    -1 => error,
    -3 => enotfound,
    -4 => eexists,
    -5 => eambiguous,
    -6 => ebufs,
    -7 => euser,
    -8 => ebarerepo,
    -9 => eunbornbranch,
    -10 => eunmerged,
    -11 => enonfastforward,
    -12 => einvalidspec,
    -13 => econflict,
    -14 => elocked,
    -15 => emodified,
    -16 => eauth,
    -17 => ecertificate,
    -18 => eapplied,
    -19 => epeel,
    -20 => eeof,
    -21 => einvalid,
    -22 => euncommitted,
    -23 => edirectory,
    -24 => emergeconflict,
    -30 => passthrough,
    -31 => iterover,
    -32 => retry,
    -33 => emismatch,
    -34 => eindexdirty,
    -35 => eapplyfail,
    -36 => eowner,
    -37 => timeout,
    -38 => eunchanged,
    -39 => enotsupported,
    -40 => ereadonly,
    _ => throw ArgumentError('Unknown value for ErrorCode: $value'),
  };
}

/// Error classes are the category of error. They reflect the area of the
/// code where an error occurred.
enum ErrorT {
  none(0),
  nomemory(1),
  os(2),
  invalid(3),
  reference(4),
  zlib(5),
  repository(6),
  config(7),
  regex(8),
  odb(9),
  index$(10),
  object(11),
  net(12),
  tag(13),
  tree(14),
  indexer(15),
  ssl(16),
  submodule(17),
  thread(18),
  stash(19),
  checkout(20),
  fetchhead(21),
  merge(22),
  ssh(23),
  filter(24),
  revert(25),
  callback(26),
  cherrypick(27),
  describe(28),
  rebase(29),
  filesystem(30),
  patch(31),
  worktree(32),
  sha(33),
  http(34),
  internal(35),
  grafts(36);

  final int value;
  const ErrorT(this.value);

  static ErrorT fromValue(int value) => switch (value) {
    0 => none,
    1 => nomemory,
    2 => os,
    3 => invalid,
    4 => reference,
    5 => zlib,
    6 => repository,
    7 => config,
    8 => regex,
    9 => odb,
    10 => index$,
    11 => object,
    12 => net,
    13 => tag,
    14 => tree,
    15 => indexer,
    16 => ssl,
    17 => submodule,
    18 => thread,
    19 => stash,
    20 => checkout,
    21 => fetchhead,
    22 => merge,
    23 => ssh,
    24 => filter,
    25 => revert,
    26 => callback,
    27 => cherrypick,
    28 => describe,
    29 => rebase,
    30 => filesystem,
    31 => patch,
    32 => worktree,
    33 => sha,
    34 => http,
    35 => internal,
    36 => grafts,
    _ => throw ArgumentError('Unknown value for ErrorT: $value'),
  };
}

/// Configurable features of libgit2; either optional settings (like
/// threading), or features that can be enabled by one of a number of
/// different backend "providers" (like HTTPS, which can be provided by
/// OpenSSL, mbedTLS, or system libraries).
enum Feature {
  /// libgit2 is thread-aware and can be used from multiple threads
  /// (as described in the documentation).
  threads(1),

  /// HTTPS remotes
  https(2),

  /// SSH remotes
  ssh(4),

  /// Sub-second resolution in index timestamps
  nsec(8),

  /// HTTP parsing; always available
  httpParser(16),

  /// Regular expression support; always available
  regex(32),

  /// Internationalization support for filename translation
  i18n(64),

  /// NTLM support over HTTPS
  authNtlm(128),

  /// Kerberos (SPNEGO) authentication support over HTTPS
  authNegotiate(256),

  /// zlib support; always available
  compression(512),

  /// SHA1 object support; always available
  sha1(1024),

  /// SHA256 object support
  sha256(2048);

  final int value;
  const Feature(this.value);

  static Feature fromValue(int value) => switch (value) {
    1 => threads,
    2 => https,
    4 => ssh,
    8 => nsec,
    16 => httpParser,
    32 => regex,
    64 => i18n,
    128 => authNtlm,
    256 => authNegotiate,
    512 => compression,
    1024 => sha1,
    2048 => sha256,
    _ => throw ArgumentError('Unknown value for Feature: $value'),
  };
}

/// Constants for fetch depth (shallowness of fetch).
enum FetchDepth {
  /// The fetch is "full" (not shallow). This is the default.
  full(0),

  /// The fetch should "unshallow" and fetch missing data.
  unshallow(2147483647);

  final int value;
  const FetchDepth(this.value);

  static FetchDepth fromValue(int value) => switch (value) {
    0 => full,
    2147483647 => unshallow,
    _ => throw ArgumentError('Unknown value for FetchDepth: $value'),
  };
}

/// Acceptable prune settings when fetching
enum FetchPrune {
  /// Use the setting from the configuration
  pruneUnspecified(0),

  /// Force pruning on
  prune(1),

  /// Force pruning off
  noPrune(2);

  final int value;
  const FetchPrune(this.value);

  static FetchPrune fromValue(int value) => switch (value) {
    0 => pruneUnspecified,
    1 => prune,
    2 => noPrune,
    _ => throw ArgumentError('Unknown value for FetchPrune: $value'),
  };
}

/// Valid modes for index and tree entries.
enum Filemode {
  unreadable(0),
  tree(16384),
  blob(33188),
  blobExecutable(33261),
  link(40960),
  commit(57344);

  final int value;
  const Filemode(this.value);

  static Filemode fromValue(int value) => switch (value) {
    0 => unreadable,
    16384 => tree,
    33188 => blob,
    33261 => blobExecutable,
    40960 => link,
    57344 => commit,
    _ => throw ArgumentError('Unknown value for Filemode: $value'),
  };
}

/// Filter option flags.
enum FilterFlag {
  default$(0),

  /// Don't error for `safecrlf` violations, allow them to continue.
  allowUnsafe(1),

  /// Don't load `/etc/gitattributes` (or the system equivalent)
  noSystemAttributes(2),

  /// Load attributes from `.gitattributes` in the root of HEAD
  attributesFromHead(4),

  /// Load attributes from `.gitattributes` in a given commit.
  /// This can only be specified in a `filter_options`.
  attributesFromCommit(8);

  final int value;
  const FilterFlag(this.value);

  static FilterFlag fromValue(int value) => switch (value) {
    0 => default$,
    1 => allowUnsafe,
    2 => noSystemAttributes,
    4 => attributesFromHead,
    8 => attributesFromCommit,
    _ => throw ArgumentError('Unknown value for FilterFlag: $value'),
  };
}

/// Filters are applied in one of two directions: smudging - which is
/// exporting a file from the Git object database to the working directory,
/// and cleaning - which is importing a file from the working directory to
/// the Git object database.  These values control which direction of
/// change is being applied.
enum FilterMode {
  toWorktree(0),
  toOdb(1);

  static const smudge = toWorktree;
  static const clean = toOdb;

  final int value;
  const FilterMode(this.value);

  static FilterMode fromValue(int value) => switch (value) {
    0 => toWorktree,
    1 => toOdb,
    _ => throw ArgumentError('Unknown value for FilterMode: $value'),
  };

  @override
  String toString() {
    if (this == toWorktree) return "FilterMode.toWorktree, FilterMode.smudge";
    if (this == toOdb) return "FilterMode.toOdb, FilterMode.clean";
    return super.toString();
  }
}

/// Flags for APIs that add files matching pathspec
enum IndexAddOption {
  default$(0),
  force(1),
  disablePathspecMatch(2),
  checkPathspec(4);

  final int value;
  const IndexAddOption(this.value);

  static IndexAddOption fromValue(int value) => switch (value) {
    0 => default$,
    1 => force,
    2 => disablePathspecMatch,
    4 => checkPathspec,
    _ => throw ArgumentError('Unknown value for IndexAddOption: $value'),
  };
}

/// Capabilities of system that affect index actions.
enum IndexCapability {
  ignoreCase(1),
  noFilemode(2),
  noSymlinks(4),
  fromOwner(-1);

  final int value;
  const IndexCapability(this.value);

  static IndexCapability fromValue(int value) => switch (value) {
    1 => ignoreCase,
    2 => noFilemode,
    4 => noSymlinks,
    -1 => fromOwner,
    _ => throw ArgumentError('Unknown value for IndexCapability: $value'),
  };
}

/// Bitmasks for on-disk fields of `index_entry`'s `flags_extended`
///
/// In memory, the `flags_extended` fields are divided into two parts: the
/// fields that are read from and written to disk, and other fields that
/// in-memory only and used by libgit2.  Only the flags in
/// `GIT_INDEX_ENTRY_EXTENDED_FLAGS` will get saved on-disk.
///
/// Thee first three bitmasks match the three fields in the
/// `index_entry` `flags_extended` value that belong on disk.  You
/// can use them to interpret the data in the `flags_extended`.
///
/// The rest of the bitmasks match the other fields in the `index_entry`
/// `flags_extended` value that are only used in-memory by libgit2.
/// You can use them to interpret the data in the `flags_extended`.
enum IndexEntryExtendedFlag {
  intentToAdd(8192),
  skipWorktree(16384),
  extendedFlags(24576),
  uptodate(4);

  final int value;
  const IndexEntryExtendedFlag(this.value);

  static IndexEntryExtendedFlag fromValue(int value) => switch (value) {
    8192 => intentToAdd,
    16384 => skipWorktree,
    24576 => extendedFlags,
    4 => uptodate,
    _ => throw ArgumentError(
      'Unknown value for IndexEntryExtendedFlag: $value',
    ),
  };
}

/// Flags for index entries
enum IndexEntryFlag {
  extended(16384),
  valid(32768);

  final int value;
  const IndexEntryFlag(this.value);

  static IndexEntryFlag fromValue(int value) => switch (value) {
    16384 => extended,
    32768 => valid,
    _ => throw ArgumentError('Unknown value for IndexEntryFlag: $value'),
  };
}

/// Git index stage states
enum IndexStage {
  /// Match any index stage.
  ///
  /// Some index APIs take a stage to match; pass this value to match
  /// any entry matching the path regardless of stage.
  any(-1),

  /// A normal staged file in the index.
  normal(0),

  /// The ancestor side of a conflict.
  ancestor(1),

  /// The "ours" side of a conflict.
  ours(2),

  /// The "theirs" side of a conflict.
  theirs(3);

  final int value;
  const IndexStage(this.value);

  static IndexStage fromValue(int value) => switch (value) {
    -1 => any,
    0 => normal,
    1 => ancestor,
    2 => ours,
    3 => theirs,
    _ => throw ArgumentError('Unknown value for IndexStage: $value'),
  };
}

/// Global library options
///
/// These are used to select which global option to set or get and are
/// used in `libgit2_opts()`.
enum Libgit2Opt {
  getMwindowSize(0),
  setMwindowSize(1),
  getMwindowMappedLimit(2),
  setMwindowMappedLimit(3),
  getSearchPath(4),
  setSearchPath(5),
  setCacheObjectLimit(6),
  setCacheMaxSize(7),
  enableCaching(8),
  getCachedMemory(9),
  getTemplatePath(10),
  setTemplatePath(11),
  setSslCertLocations(12),
  setUserAgent(13),
  enableStrictObjectCreation(14),
  enableStrictSymbolicRefCreation(15),
  setSslCiphers(16),
  getUserAgent(17),
  enableOfsDelta(18),
  enableFsyncGitdir(19),
  getWindowsSharemode(20),
  setWindowsSharemode(21),
  enableStrictHashVerification(22),
  setAllocator(23),
  enableUnsavedIndexSafety(24),
  getPackMaxObjects(25),
  setPackMaxObjects(26),
  disablePackKeepFileChecks(27),
  enableHttpExpectContinue(28),
  getMwindowFileLimit(29),
  setMwindowFileLimit(30),
  setOdbPackedPriority(31),
  setOdbLoosePriority(32),
  getExtensions(33),
  setExtensions(34),
  getOwnerValidation(35),
  setOwnerValidation(36),
  getHomedir(37),
  setHomedir(38),
  setServerConnectTimeout(39),
  getServerConnectTimeout(40),
  setServerTimeout(41),
  getServerTimeout(42),
  setUserAgentProduct(43),
  getUserAgentProduct(44),
  addSslX509Cert(45);

  final int value;
  const Libgit2Opt(this.value);

  static Libgit2Opt fromValue(int value) => switch (value) {
    0 => getMwindowSize,
    1 => setMwindowSize,
    2 => getMwindowMappedLimit,
    3 => setMwindowMappedLimit,
    4 => getSearchPath,
    5 => setSearchPath,
    6 => setCacheObjectLimit,
    7 => setCacheMaxSize,
    8 => enableCaching,
    9 => getCachedMemory,
    10 => getTemplatePath,
    11 => setTemplatePath,
    12 => setSslCertLocations,
    13 => setUserAgent,
    14 => enableStrictObjectCreation,
    15 => enableStrictSymbolicRefCreation,
    16 => setSslCiphers,
    17 => getUserAgent,
    18 => enableOfsDelta,
    19 => enableFsyncGitdir,
    20 => getWindowsSharemode,
    21 => setWindowsSharemode,
    22 => enableStrictHashVerification,
    23 => setAllocator,
    24 => enableUnsavedIndexSafety,
    25 => getPackMaxObjects,
    26 => setPackMaxObjects,
    27 => disablePackKeepFileChecks,
    28 => enableHttpExpectContinue,
    29 => getMwindowFileLimit,
    30 => setMwindowFileLimit,
    31 => setOdbPackedPriority,
    32 => setOdbLoosePriority,
    33 => getExtensions,
    34 => setExtensions,
    35 => getOwnerValidation,
    36 => setOwnerValidation,
    37 => getHomedir,
    38 => setHomedir,
    39 => setServerConnectTimeout,
    40 => getServerConnectTimeout,
    41 => setServerTimeout,
    42 => getServerTimeout,
    43 => setUserAgentProduct,
    44 => getUserAgentProduct,
    45 => addSslX509Cert,
    _ => throw ArgumentError('Unknown value for Libgit2Opt: $value'),
  };
}

/// The results of `merge_analysis` indicate the merge opportunities.
enum MergeAnalysis {
  /// No merge is possible.  (Unused.)
  none(0),

  /// A "normal" merge; both HEAD and the given merge input have diverged
  /// from their common ancestor.  The divergent commits must be merged.
  normal(1),

  /// All given merge inputs are reachable from HEAD, meaning the
  /// repository is up-to-date and no merge needs to be performed.
  upToDate(2),

  /// The given merge input is a fast-forward from HEAD and no merge
  /// needs to be performed.  Instead, the client can check out the
  /// given merge input.
  fastforward(4),

  /// The HEAD of the current repository is "unborn" and does not point to
  /// a valid commit.  No merge can be performed, but the caller may wish
  /// to simply set HEAD to the target commit(s).
  unborn(8);

  final int value;
  const MergeAnalysis(this.value);

  static MergeAnalysis fromValue(int value) => switch (value) {
    0 => none,
    1 => normal,
    2 => upToDate,
    4 => fastforward,
    8 => unborn,
    _ => throw ArgumentError('Unknown value for MergeAnalysis: $value'),
  };
}

/// Merge file favor options for `merge_options` instruct the file-level
/// merging functionality how to deal with conflicting regions of the files.
enum MergeFileFavor {
  /// When a region of a file is changed in both branches, a conflict
  /// will be recorded in the index so that `checkout` can produce
  /// a merge file with conflict markers in the working directory.
  /// This is the default.
  normal(0),

  /// When a region of a file is changed in both branches, the file
  /// created in the index will contain the "ours" side of any conflicting
  /// region.  The index will not record a conflict.
  ours(1),

  /// When a region of a file is changed in both branches, the file
  /// created in the index will contain the "theirs" side of any conflicting
  /// region.  The index will not record a conflict.
  theirs(2),

  /// When a region of a file is changed in both branches, the file
  /// created in the index will contain each unique line from each side,
  /// which has the result of combining both files.  The index will not
  /// record a conflict.
  union(3);

  final int value;
  const MergeFileFavor(this.value);

  static MergeFileFavor fromValue(int value) => switch (value) {
    0 => normal,
    1 => ours,
    2 => theirs,
    3 => union,
    _ => throw ArgumentError('Unknown value for MergeFileFavor: $value'),
  };
}

/// File merging flags
enum MergeFileFlag {
  /// Defaults
  default$(0),

  /// Create standard conflicted merge files
  styleMerge(1),

  /// Create diff3-style files
  styleDiff3(2),

  /// Condense non-alphanumeric regions for simplified diff file
  simplifyAlnum(4),

  /// Ignore all whitespace
  ignoreWhitespace(8),

  /// Ignore changes in amount of whitespace
  ignoreWhitespaceChange(16),

  /// Ignore whitespace at end of line
  ignoreWhitespaceEol(32),

  /// Use the "patience diff" algorithm
  diffPatience(64),

  /// Take extra time to find minimal diff
  diffMinimal(128),

  /// Create zdiff3 ("zealous diff3")-style files
  styleZdiff3(256),

  /// Do not produce file conflicts when common regions have
  /// changed; keep the conflict markers in the file and accept
  /// that as the merge result.
  acceptConflicts(512);

  final int value;
  const MergeFileFlag(this.value);

  static MergeFileFlag fromValue(int value) => switch (value) {
    0 => default$,
    1 => styleMerge,
    2 => styleDiff3,
    4 => simplifyAlnum,
    8 => ignoreWhitespace,
    16 => ignoreWhitespaceChange,
    32 => ignoreWhitespaceEol,
    64 => diffPatience,
    128 => diffMinimal,
    256 => styleZdiff3,
    512 => acceptConflicts,
    _ => throw ArgumentError('Unknown value for MergeFileFlag: $value'),
  };
}

/// Flags for `merge` options.  A combination of these flags can be
/// passed in via the `flags` value in the `merge_options`.
enum MergeFlag {
  /// Detect renames that occur between the common ancestor and the "ours"
  /// side or the common ancestor and the "theirs" side.  This will enable
  /// the ability to merge between a modified and renamed file.
  findRenames(1),

  /// If a conflict occurs, exit immediately instead of attempting to
  /// continue resolving conflicts.  The merge operation will fail with
  /// GIT_EMERGECONFLICT and no index will be returned.
  failOnConflict(2),

  /// Do not write the REUC extension on the generated index
  skipReuc(4),

  /// If the commits being merged have multiple merge bases, do not build
  /// a recursive merge base (by merging the multiple merge bases),
  /// instead simply use the first base.  This flag provides a similar
  /// merge base to `git-merge-resolve`.
  noRecursive(8),

  /// Treat this merge as if it is to produce the virtual base
  /// of a recursive merge.  This will ensure that there are
  /// no conflicts, any conflicting regions will keep conflict
  /// markers in the merge result.
  virtualBase(16);

  final int value;
  const MergeFlag(this.value);

  static MergeFlag fromValue(int value) => switch (value) {
    1 => findRenames,
    2 => failOnConflict,
    4 => skipReuc,
    8 => noRecursive,
    16 => virtualBase,
    _ => throw ArgumentError('Unknown value for MergeFlag: $value'),
  };
}

/// The user's stated preference for merges.
enum MergePreference {
  /// No configuration was found that suggests a preferred behavior for
  /// merge.
  none(0),

  /// There is a `merge.ff=false` configuration setting, suggesting that
  /// the user does not want to allow a fast-forward merge.
  noFastforward(1),

  /// There is a `merge.ff=only` configuration setting, suggesting that
  /// the user only wants fast-forward merges.
  fastforwardOnly(2);

  final int value;
  const MergePreference(this.value);

  static MergePreference fromValue(int value) => switch (value) {
    0 => none,
    1 => noFastforward,
    2 => fastforwardOnly,
    _ => throw ArgumentError('Unknown value for MergePreference: $value'),
  };
}

/// Basic type (loose or packed) of any Git object.
enum ObjectT {
  /// < Object can be any of the following
  any(-2),

  /// < Object is invalid.
  invalid(-1),

  /// < A commit object.
  commit(1),

  /// < A tree (directory listing) object.
  tree(2),

  /// < A file revision object.
  blob(3),

  /// < An annotated tag object.
  tag(4),

  /// < A delta, base is given by an offset.
  ofsDelta(6),

  /// < A delta, base is given by object id.
  refDelta(7);

  final int value;
  const ObjectT(this.value);

  static ObjectT fromValue(int value) => switch (value) {
    -2 => any,
    -1 => invalid,
    1 => commit,
    2 => tree,
    3 => blob,
    4 => tag,
    6 => ofsDelta,
    7 => refDelta,
    _ => throw ArgumentError('Unknown value for ObjectT: $value'),
  };
}

enum OdbBackendLooseFlag {
  fsync(1);

  final int value;
  const OdbBackendLooseFlag(this.value);

  static OdbBackendLooseFlag fromValue(int value) => switch (value) {
    1 => fsync,
    _ => throw ArgumentError('Unknown value for OdbBackendLooseFlag: $value'),
  };
}

/// Flags controlling the behavior of ODB lookup operations
enum OdbLookupFlags {
  /// Don't call `odb_refresh` if the lookup fails. Useful when doing
  /// a batch of lookup operations for objects that may legitimately not
  /// exist. When using this flag, you may wish to manually call
  /// `odb_refresh` before processing a batch of objects.
  refresh(1);

  final int value;
  const OdbLookupFlags(this.value);

  static OdbLookupFlags fromValue(int value) => switch (value) {
    1 => refresh,
    _ => throw ArgumentError('Unknown value for OdbLookupFlags: $value'),
  };
}

/// Streaming mode
enum OdbStreamT {
  rdonly(2),
  wronly(4),
  rw(6);

  final int value;
  const OdbStreamT(this.value);

  static OdbStreamT fromValue(int value) => switch (value) {
    2 => rdonly,
    4 => wronly,
    6 => rw,
    _ => throw ArgumentError('Unknown value for OdbStreamT: $value'),
  };
}

/// The type of object id.
enum OidT {
  /// < SHA1
  sha1(1);

  final int value;
  const OidT(this.value);

  static OidT fromValue(int value) => switch (value) {
    1 => sha1,
    _ => throw ArgumentError('Unknown value for OidT: $value'),
  };
}

/// Stages that are reported by the packbuilder progress callback.
enum PackbuilderStage {
  addingObjects(0),
  deltafication(1);

  final int value;
  const PackbuilderStage(this.value);

  static PackbuilderStage fromValue(int value) => switch (value) {
    0 => addingObjects,
    1 => deltafication,
    _ => throw ArgumentError('Unknown value for PackbuilderStage: $value'),
  };
}

/// Options controlling how pathspec match should be executed
enum PathspecFlag {
  default$(0),

  /// GIT_PATHSPEC_IGNORE_CASE forces match to ignore case; otherwise
  /// match will use native case sensitivity of platform filesystem
  ignoreCase(1),

  /// GIT_PATHSPEC_USE_CASE forces case sensitive match; otherwise
  /// match will use native case sensitivity of platform filesystem
  useCase(2),

  /// GIT_PATHSPEC_NO_GLOB disables glob patterns and just uses simple
  /// string comparison for matching
  noGlob(4),

  /// GIT_PATHSPEC_NO_MATCH_ERROR means the match functions return error
  /// code GIT_ENOTFOUND if no matches are found; otherwise no matches is
  /// still success (return 0) but `pathspec_match_list_entrycount`
  /// will indicate 0 matches.
  noMatchError(8),

  /// GIT_PATHSPEC_FIND_FAILURES means that the `pathspec_match_list`
  /// should track which patterns matched which files so that at the end of
  /// the match we can identify patterns that did not match any files.
  findFailures(16),

  /// GIT_PATHSPEC_FAILURES_ONLY means that the `pathspec_match_list`
  /// does not need to keep the actual matching filenames.  Use this to
  /// just test if there were any matches at all or in combination with
  /// GIT_PATHSPEC_FIND_FAILURES to validate a pathspec.
  failuresOnly(32);

  final int value;
  const PathspecFlag(this.value);

  static PathspecFlag fromValue(int value) => switch (value) {
    0 => default$,
    1 => ignoreCase,
    2 => useCase,
    4 => noGlob,
    8 => noMatchError,
    16 => findFailures,
    32 => failuresOnly,
    _ => throw ArgumentError('Unknown value for PathspecFlag: $value'),
  };
}

/// The type of proxy to use.
enum Proxy {
  /// Do not attempt to connect through a proxy
  ///
  /// If built against libcurl, it itself may attempt to connect
  /// to a proxy if the environment variables specify it.
  none(0),

  /// Try to auto-detect the proxy from the git configuration.
  auto(1),

  /// Connect via the URL given in the options
  specified(2);

  final int value;
  const Proxy(this.value);

  static Proxy fromValue(int value) => switch (value) {
    0 => none,
    1 => auto,
    2 => specified,
    _ => throw ArgumentError('Unknown value for Proxy: $value'),
  };
}

/// Type of rebase operation in-progress after calling `rebase_next`.
enum RebaseOperationT {
  /// The given commit is to be cherry-picked.  The client should commit
  /// the changes and continue if there are no conflicts.
  pick(0),

  /// The given commit is to be cherry-picked, but the client should prompt
  /// the user to provide an updated commit message.
  reword(1),

  /// The given commit is to be cherry-picked, but the client should stop
  /// to allow the user to edit the changes before committing them.
  edit(2),

  /// The given commit is to be squashed into the previous commit.  The
  /// commit message will be merged with the previous message.
  squash(3),

  /// The given commit is to be squashed into the previous commit.  The
  /// commit message from this commit will be discarded.
  fixup(4),

  /// No commit will be cherry-picked.  The client should run the given
  /// command and (if successful) continue.
  exec(5);

  final int value;
  const RebaseOperationT(this.value);

  static RebaseOperationT fromValue(int value) => switch (value) {
    0 => pick,
    1 => reword,
    2 => edit,
    3 => squash,
    4 => fixup,
    5 => exec,
    _ => throw ArgumentError('Unknown value for RebaseOperationT: $value'),
  };
}

/// Normalization options for reference lookup
enum ReferenceFormat {
  /// No particular normalization.
  normal(0),

  /// Control whether one-level refnames are accepted
  /// (i.e., refnames that do not contain multiple /-separated
  /// components). Those are expected to be written only using
  /// uppercase letters and underscore (FETCH_HEAD, ...)
  allowOnelevel(1),

  /// Interpret the provided name as a reference pattern for a
  /// refspec (as used with remote repositories). If this option
  /// is enabled, the name is allowed to contain a single * (<star>)
  /// in place of a one full pathname component
  /// (e.g., foo/<star>/bar but not foo/bar<star>).
  refspecPattern(2),

  /// Interpret the name as part of a refspec in shorthand form
  /// so the `ONELEVEL` naming rules aren't enforced and 'master'
  /// becomes a valid name.
  refspecShorthand(4);

  final int value;
  const ReferenceFormat(this.value);

  static ReferenceFormat fromValue(int value) => switch (value) {
    0 => normal,
    1 => allowOnelevel,
    2 => refspecPattern,
    4 => refspecShorthand,
    _ => throw ArgumentError('Unknown value for ReferenceFormat: $value'),
  };
}

/// Basic type of any Git reference.
enum ReferenceT {
  /// < Invalid reference
  invalid(0),

  /// < A reference that points at an object id
  direct(1),

  /// < A reference that points at another reference
  symbolic(2),
  all(3);

  final int value;
  const ReferenceT(this.value);

  static ReferenceT fromValue(int value) => switch (value) {
    0 => invalid,
    1 => direct,
    2 => symbolic,
    3 => all,
    _ => throw ArgumentError('Unknown value for ReferenceT: $value'),
  };
}

/// Automatic tag following option
///
/// Lets us select the --tags option to use.
enum RemoteAutotagOption {
  /// Use the setting from the configuration.
  unspecified(0),

  /// Ask the server for tags pointing to objects we're already
  /// downloading.
  auto(1),

  /// Don't ask for any tags beyond the refspecs.
  none(2),

  /// Ask for the all the tags.
  all(3);

  final int value;
  const RemoteAutotagOption(this.value);

  static RemoteAutotagOption fromValue(int value) => switch (value) {
    0 => unspecified,
    1 => auto,
    2 => none,
    3 => all,
    _ => throw ArgumentError('Unknown value for RemoteAutotagOption: $value'),
  };
}

/// Argument to the completion callback which tells it which operation
/// finished.
enum RemoteCompletion {
  download(0),
  indexing(1),
  error(2);

  final int value;
  const RemoteCompletion(this.value);

  static RemoteCompletion fromValue(int value) => switch (value) {
    0 => download,
    1 => indexing,
    2 => error,
    _ => throw ArgumentError('Unknown value for RemoteCompletion: $value'),
  };
}

/// Remote creation options flags
enum RemoteCreateFlags {
  /// Ignore the repository apply.insteadOf configuration
  insteadof(1),

  /// Don't build a fetchspec from the name if none is set
  defaultFetchspec(2);

  final int value;
  const RemoteCreateFlags(this.value);

  static RemoteCreateFlags fromValue(int value) => switch (value) {
    1 => insteadof,
    2 => defaultFetchspec,
    _ => throw ArgumentError('Unknown value for RemoteCreateFlags: $value'),
  };
}

/// Remote redirection settings; whether redirects to another host
/// are permitted.  By default, git will follow a redirect on the
/// initial request (`/info/refs`), but not subsequent requests.
enum RemoteRedirect {
  /// Do not follow any off-site redirects at any stage of
  /// the fetch or push.
  none(1),

  /// Allow off-site redirects only upon the initial request.
  /// This is the default.
  initial(2),

  /// Allow redirects at any stage in the fetch or push.
  all(4);

  final int value;
  const RemoteRedirect(this.value);

  static RemoteRedirect fromValue(int value) => switch (value) {
    1 => none,
    2 => initial,
    4 => all,
    _ => throw ArgumentError('Unknown value for RemoteRedirect: $value'),
  };
}

/// How to handle reference updates.
enum RemoteUpdateFlags {
  fetchhead(1),
  reportUnchanged(2);

  final int value;
  const RemoteUpdateFlags(this.value);

  static RemoteUpdateFlags fromValue(int value) => switch (value) {
    1 => fetchhead,
    2 => reportUnchanged,
    _ => throw ArgumentError('Unknown value for RemoteUpdateFlags: $value'),
  };
}

/// Option flags for `repository_init_ext`.
///
/// These flags configure extra behaviors to `repository_init_ext`.
/// In every case, the default behavior is the zero value (i.e. flag is
/// not set). Just OR the flag values together for the `flags` parameter
/// when initializing a new repo.
enum RepositoryInitFlag {
  /// Create a bare repository with no working directory.
  bare(1),

  /// Return an GIT_EEXISTS error if the repo_path appears to already be
  /// an git repository.
  noReinit(2),

  /// Normally a "/.git/" will be appended to the repo path for
  /// non-bare repos (if it is not already there), but passing this flag
  /// prevents that behavior.
  noDotgitDir(4),

  /// Make the repo_path (and workdir_path) as needed. Init is always willing
  /// to create the ".git" directory even without this flag. This flag tells
  /// init to create the trailing component of the repo and workdir paths
  /// as needed.
  mkdir(8),

  /// Recursively make all components of the repo and workdir paths as
  /// necessary.
  mkpath(16),

  /// libgit2 normally uses internal templates to initialize a new repo.
  /// This flags enables external templates, looking the "template_path" from
  /// the options if set, or the `init.templatedir` global config if not,
  /// or falling back on "/usr/share/git-core/templates" if it exists.
  externalTemplate(32),

  /// If an alternate workdir is specified, use relative paths for the gitdir
  /// and core.worktree.
  relativeGitlink(64);

  final int value;
  const RepositoryInitFlag(this.value);

  static RepositoryInitFlag fromValue(int value) => switch (value) {
    1 => bare,
    2 => noReinit,
    4 => noDotgitDir,
    8 => mkdir,
    16 => mkpath,
    32 => externalTemplate,
    64 => relativeGitlink,
    _ => throw ArgumentError('Unknown value for RepositoryInitFlag: $value'),
  };
}

/// Mode options for `repository_init_ext`.
///
/// Set the mode field of the `repository_init_options` structure
/// either to the custom mode that you would like, or to one of the
/// defined modes.
enum RepositoryInitMode {
  /// Use permissions configured by umask - the default.
  umask(0),

  /// Use "--shared=group" behavior, chmod'ing the new repo to be group
  /// writable and "g+sx" for sticky group assignment.
  group(1533),

  /// Use "--shared=all" behavior, adding world readability.
  all(1535);

  final int value;
  const RepositoryInitMode(this.value);

  static RepositoryInitMode fromValue(int value) => switch (value) {
    0 => umask,
    1533 => group,
    1535 => all,
    _ => throw ArgumentError('Unknown value for RepositoryInitMode: $value'),
  };
}

/// List of items which belong to the git repository layout
enum RepositoryItem {
  gitdir(0),
  workdir(1),
  commondir(2),
  index$(3),
  objects(4),
  refs(5),
  packedRefs(6),
  remotes(7),
  config(8),
  info(9),
  hooks(10),
  logs(11),
  modules(12),
  worktrees(13),
  worktreeConfig(14),
  Last(15);

  final int value;
  const RepositoryItem(this.value);

  static RepositoryItem fromValue(int value) => switch (value) {
    0 => gitdir,
    1 => workdir,
    2 => commondir,
    3 => index$,
    4 => objects,
    5 => refs,
    6 => packedRefs,
    7 => remotes,
    8 => config,
    9 => info,
    10 => hooks,
    11 => logs,
    12 => modules,
    13 => worktrees,
    14 => worktreeConfig,
    15 => Last,
    _ => throw ArgumentError('Unknown value for RepositoryItem: $value'),
  };
}

/// Option flags for `repository_open_ext`.
enum RepositoryOpenFlag {
  /// Only open the repository if it can be immediately found in the
  /// start_path. Do not walk up from the start_path looking at parent
  /// directories.
  noSearch(1),

  /// Unless this flag is set, open will not continue searching across
  /// filesystem boundaries (i.e. when `st_dev` changes from the `stat`
  /// system call).  For example, searching in a user's home directory at
  /// "/home/user/source/" will not return "/.git/" as the found repo if
  /// "/" is a different filesystem than "/home".
  crossFs(2),

  /// Open repository as a bare repo regardless of core.bare config, and
  /// defer loading config file for faster setup.
  /// Unlike `repository_open_bare`, this can follow gitlinks.
  bare(4),

  /// Do not check for a repository by appending /.git to the start_path;
  /// only open the repository if start_path itself points to the git
  /// directory.
  noDotgit(8),

  /// Find and open a git repository, respecting the environment variables
  /// used by the git command-line tools.
  /// If set, `repository_open_ext` will ignore the other flags and
  /// the `ceiling_dirs` argument, and will allow a NULL `path` to use
  /// `GIT_DIR` or search from the current directory.
  /// The search for a repository will respect $GIT_CEILING_DIRECTORIES and
  /// $GIT_DISCOVERY_ACROSS_FILESYSTEM.  The opened repository will
  /// respect $GIT_INDEX_FILE, $GIT_NAMESPACE, $GIT_OBJECT_DIRECTORY, and
  /// $GIT_ALTERNATE_OBJECT_DIRECTORIES.
  /// In the future, this flag will also cause `repository_open_ext`
  /// to respect $GIT_WORK_TREE and $GIT_COMMON_DIR; currently,
  /// `repository_open_ext` with this flag will error out if either
  /// $GIT_WORK_TREE or $GIT_COMMON_DIR is set.
  fromEnv(16);

  final int value;
  const RepositoryOpenFlag(this.value);

  static RepositoryOpenFlag fromValue(int value) => switch (value) {
    1 => noSearch,
    2 => crossFs,
    4 => bare,
    8 => noDotgit,
    16 => fromEnv,
    _ => throw ArgumentError('Unknown value for RepositoryOpenFlag: $value'),
  };
}

/// Repository state
///
/// These values represent possible states for the repository to be in,
/// based on the current operation which is ongoing.
enum RepositoryState {
  none(0),
  merge(1),
  revert(2),
  revertSequence(3),
  cherrypick(4),
  cherrypickSequence(5),
  bisect(6),
  rebase(7),
  rebaseInteractive(8),
  rebaseMerge(9),
  applyMailbox(10),
  applyMailboxOrRebase(11);

  final int value;
  const RepositoryState(this.value);

  static RepositoryState fromValue(int value) => switch (value) {
    0 => none,
    1 => merge,
    2 => revert,
    3 => revertSequence,
    4 => cherrypick,
    5 => cherrypickSequence,
    6 => bisect,
    7 => rebase,
    8 => rebaseInteractive,
    9 => rebaseMerge,
    10 => applyMailbox,
    11 => applyMailboxOrRebase,
    _ => throw ArgumentError('Unknown value for RepositoryState: $value'),
  };
}

/// Kinds of reset operation
enum Reset {
  /// < Move the head to the given commit
  soft(1),

  /// < SOFT plus reset index to the commit
  mixed(2),

  /// < MIXED plus changes in working tree discarded
  hard(3);

  final int value;
  const Reset(this.value);

  static Reset fromValue(int value) => switch (value) {
    1 => soft,
    2 => mixed,
    3 => hard,
    _ => throw ArgumentError('Unknown value for Reset: $value'),
  };
}

/// Revparse flags.  These indicate the intended behavior of the spec passed to
/// revparse.
enum RevspecT {
  /// The spec targeted a single object.
  single(1),

  /// The spec targeted a range of commits.
  range(2),

  /// The spec used the '...' operator, which invokes special semantics.
  mergeBase(4);

  final int value;
  const RevspecT(this.value);

  static RevspecT fromValue(int value) => switch (value) {
    1 => single,
    2 => range,
    4 => mergeBase,
    _ => throw ArgumentError('Unknown value for RevspecT: $value'),
  };
}

/// Flags to specify the sorting which a revwalk should perform.
enum Sort {
  /// Sort the output with the same default method from `git`: reverse
  /// chronological order. This is the default sorting for new walkers.
  none(0),

  /// Sort the repository contents in topological order (no parents before
  /// all of its children are shown); this sorting mode can be combined
  /// with time sorting to produce `git`'s `--date-order``.
  topological(1),

  /// Sort the repository contents by commit time;
  /// this sorting mode can be combined with
  /// topological sorting.
  time(2),

  /// Iterate through the repository contents in reverse
  /// order; this sorting mode can be combined with
  /// any of the above.
  reverse(4);

  final int value;
  const Sort(this.value);

  static Sort fromValue(int value) => switch (value) {
    0 => none,
    1 => topological,
    2 => time,
    4 => reverse,
    _ => throw ArgumentError('Unknown value for Sort: $value'),
  };
}

/// Stash application flags.
enum StashApplyFlags {
  default$(0),
  reinstateIndex(1);

  final int value;
  const StashApplyFlags(this.value);

  static StashApplyFlags fromValue(int value) => switch (value) {
    0 => default$,
    1 => reinstateIndex,
    _ => throw ArgumentError('Unknown value for StashApplyFlags: $value'),
  };
}

/// Stash apply progression states
enum StashApplyProgress {
  none(0),

  /// Loading the stashed data from the object database.
  loadingStash(1),

  /// The stored index is being analyzed.
  analyzeIndex(2),

  /// The modified files are being analyzed.
  analyzeModified(3),

  /// The untracked and ignored files are being analyzed.
  analyzeUntracked(4),

  /// The untracked files are being written to disk.
  checkoutUntracked(5),

  /// The modified files are being written to disk.
  checkoutModified(6),

  /// The stash was applied successfully.
  done(7);

  final int value;
  const StashApplyProgress(this.value);

  static StashApplyProgress fromValue(int value) => switch (value) {
    0 => none,
    1 => loadingStash,
    2 => analyzeIndex,
    3 => analyzeModified,
    4 => analyzeUntracked,
    5 => checkoutUntracked,
    6 => checkoutModified,
    7 => done,
    _ => throw ArgumentError('Unknown value for StashApplyProgress: $value'),
  };
}

/// Stash flags
enum StashFlags {
  /// No option, default
  default$(0),

  /// All changes already added to the index are left intact in
  /// the working directory
  keepIndex(1),

  /// All untracked files are also stashed and then cleaned up
  /// from the working directory
  includeUntracked(2),

  /// All ignored files are also stashed and then cleaned up from
  /// the working directory
  includeIgnored(4),

  /// All changes in the index and working directory are left intact
  keepAll(8);

  final int value;
  const StashFlags(this.value);

  static StashFlags fromValue(int value) => switch (value) {
    0 => default$,
    1 => keepIndex,
    2 => includeUntracked,
    4 => includeIgnored,
    8 => keepAll,
    _ => throw ArgumentError('Unknown value for StashFlags: $value'),
  };
}

/// Status flags for a single file.
///
/// A combination of these values will be returned to indicate the status of
/// a file.  Status compares the working directory, the index, and the
/// current HEAD of the repository.  The `GIT_STATUS_INDEX` set of flags
/// represents the status of file in the index relative to the HEAD, and the
/// `GIT_STATUS_WT` set of flags represent the status of the file in the
/// working directory relative to the index.
enum Status {
  current(0),
  indexNew(1),
  indexModified(2),
  indexDeleted(4),
  indexRenamed(8),
  indexTypechange(16),
  wtNew(128),
  wtModified(256),
  wtDeleted(512),
  wtTypechange(1024),
  wtRenamed(2048),
  wtUnreadable(4096),
  ignored(16384),
  conflicted(32768);

  final int value;
  const Status(this.value);

  static Status fromValue(int value) => switch (value) {
    0 => current,
    1 => indexNew,
    2 => indexModified,
    4 => indexDeleted,
    8 => indexRenamed,
    16 => indexTypechange,
    128 => wtNew,
    256 => wtModified,
    512 => wtDeleted,
    1024 => wtTypechange,
    2048 => wtRenamed,
    4096 => wtUnreadable,
    16384 => ignored,
    32768 => conflicted,
    _ => throw ArgumentError('Unknown value for Status: $value'),
  };
}

/// Flags to control status callbacks
///
/// Calling `status_foreach()` is like calling the extended version
/// with: GIT_STATUS_OPT_INCLUDE_IGNORED, GIT_STATUS_OPT_INCLUDE_UNTRACKED,
/// and GIT_STATUS_OPT_RECURSE_UNTRACKED_DIRS.  Those options are bundled
/// together as `GIT_STATUS_OPT_DEFAULTS` if you want them as a baseline.
enum StatusOpt {
  /// Says that callbacks should be made on untracked files.
  /// These will only be made if the workdir files are included in the status
  /// "show" option.
  includeUntracked(1),

  /// Says that ignored files get callbacks.
  /// Again, these callbacks will only be made if the workdir files are
  /// included in the status "show" option.
  includeIgnored(2),

  /// Indicates that callback should be made even on unmodified files.
  includeUnmodified(4),

  /// Indicates that submodules should be skipped.
  /// This only applies if there are no pending typechanges to the submodule
  /// (either from or to another type).
  excludeSubmodules(8),

  /// Indicates that all files in untracked directories should be included.
  /// Normally if an entire directory is new, then just the top-level
  /// directory is included (with a trailing slash on the entry name).
  /// This flag says to include all of the individual files in the directory
  /// instead.
  recurseUntrackedDirs(16),

  /// Indicates that the given path should be treated as a literal path,
  /// and not as a pathspec pattern.
  disablePathspecMatch(32),

  /// Indicates that the contents of ignored directories should be included
  /// in the status. This is like doing `git ls-files -o -i --exclude-standard`
  /// with core git.
  recurseIgnoredDirs(64),

  /// Indicates that rename detection should be processed between the head and
  /// the index and enables the GIT_STATUS_INDEX_RENAMED as a possible status
  /// flag.
  renamesHeadToIndex(128),

  /// Indicates that rename detection should be run between the index and the
  /// working directory and enabled GIT_STATUS_WT_RENAMED as a possible status
  /// flag.
  renamesIndexToWorkdir(256),

  /// Overrides the native case sensitivity for the file system and forces
  /// the output to be in case-sensitive order.
  sortCaseSensitively(512),

  /// Overrides the native case sensitivity for the file system and forces
  /// the output to be in case-insensitive order.
  sortCaseInsensitively(1024),

  /// Iindicates that rename detection should include rewritten files.
  renamesFromRewrites(2048),

  /// Bypasses the default status behavior of doing a "soft" index reload
  /// (i.e. reloading the index data if the file on disk has been modified
  /// outside libgit2).
  noRefresh(4096),

  /// Tells libgit2 to refresh the stat cache in the index for files that are
  /// unchanged but have out of date stat einformation in the index.
  /// It will result in less work being done on subsequent calls to get status.
  /// This is mutually exclusive with the NO_REFRESH option.
  updateIndex(8192),

  /// Normally files that cannot be opened or read are ignored as
  /// these are often transient files; this option will return
  /// unreadable files as `GIT_STATUS_WT_UNREADABLE`.
  includeUnreadable(16384),

  /// Unreadable files will be detected and given the status
  /// untracked instead of unreadable.
  includeUnreadableAsUntracked(32768);

  final int value;
  const StatusOpt(this.value);

  static StatusOpt fromValue(int value) => switch (value) {
    1 => includeUntracked,
    2 => includeIgnored,
    4 => includeUnmodified,
    8 => excludeSubmodules,
    16 => recurseUntrackedDirs,
    32 => disablePathspecMatch,
    64 => recurseIgnoredDirs,
    128 => renamesHeadToIndex,
    256 => renamesIndexToWorkdir,
    512 => sortCaseSensitively,
    1024 => sortCaseInsensitively,
    2048 => renamesFromRewrites,
    4096 => noRefresh,
    8192 => updateIndex,
    16384 => includeUnreadable,
    32768 => includeUnreadableAsUntracked,
    _ => throw ArgumentError('Unknown value for StatusOpt: $value'),
  };
}

/// Select the files on which to report status.
///
/// With `status_foreach_ext`, this will control which changes get
/// callbacks.  With `status_list_new`, these will control which
/// changes are included in the list.
enum StatusShow {
  /// The default. This roughly matches `git status --porcelain` regarding
  /// which files are included and in what order.
  indexAndWorkdir(0),

  /// Only gives status based on HEAD to index comparison, not looking at
  /// working directory changes.
  indexOnly(1),

  /// Only gives status based on index to working directory comparison,
  /// not comparing the index to the HEAD.
  workdirOnly(2);

  final int value;
  const StatusShow(this.value);

  static StatusShow fromValue(int value) => switch (value) {
    0 => indexAndWorkdir,
    1 => indexOnly,
    2 => workdirOnly,
    _ => throw ArgumentError('Unknown value for StatusShow: $value'),
  };
}

/// Submodule ignore values
///
/// These values represent settings for the `submodule.$name.ignore`
/// configuration value which says how deeply to look at the working
/// directory when getting submodule status.
///
/// You can override this value in memory on a per-submodule basis with
/// `submodule_set_ignore()` and can write the changed value to disk
/// with `submodule_save()`.  If you have overwritten the value, you
/// can revert to the on disk value by using `GIT_SUBMODULE_IGNORE_RESET`.
///
/// The values are:
///
/// - GIT_SUBMODULE_IGNORE_UNSPECIFIED: use the submodule's configuration
/// - GIT_SUBMODULE_IGNORE_NONE: don't ignore any change - i.e. even an
/// untracked file, will mark the submodule as dirty.  Ignored files are
/// still ignored, of course.
/// - GIT_SUBMODULE_IGNORE_UNTRACKED: ignore untracked files; only changes
/// to tracked files, or the index or the HEAD commit will matter.
/// - GIT_SUBMODULE_IGNORE_DIRTY: ignore changes in the working directory,
/// only considering changes if the HEAD of submodule has moved from the
/// value in the superproject.
/// - GIT_SUBMODULE_IGNORE_ALL: never check if the submodule is dirty
/// - GIT_SUBMODULE_IGNORE_DEFAULT: not used except as static initializer
/// when we don't want any particular ignore rule to be specified.
enum SubmoduleIgnore {
  /// < use the submodule's configuration
  unspecified(-1),

  /// < any change or untracked == dirty
  none(1),

  /// < dirty if tracked files change
  untracked(2),

  /// < only dirty if HEAD moved
  dirty(3),

  /// < never dirty
  all(4);

  final int value;
  const SubmoduleIgnore(this.value);

  static SubmoduleIgnore fromValue(int value) => switch (value) {
    -1 => unspecified,
    1 => none,
    2 => untracked,
    3 => dirty,
    4 => all,
    _ => throw ArgumentError('Unknown value for SubmoduleIgnore: $value'),
  };
}

/// Options for submodule recurse.
///
/// Represent the value of `submodule.$name.fetchRecurseSubmodules`
///
/// * GIT_SUBMODULE_RECURSE_NO    - do no recurse into submodules
/// * GIT_SUBMODULE_RECURSE_YES   - recurse into submodules
/// * GIT_SUBMODULE_RECURSE_ONDEMAND - recurse into submodules only when
/// commit not already in local clone
enum SubmoduleRecurse {
  no(0),
  yes(1),
  ondemand(2);

  final int value;
  const SubmoduleRecurse(this.value);

  static SubmoduleRecurse fromValue(int value) => switch (value) {
    0 => no,
    1 => yes,
    2 => ondemand,
    _ => throw ArgumentError('Unknown value for SubmoduleRecurse: $value'),
  };
}

/// Return codes for submodule status.
///
/// A combination of these flags will be returned to describe the status of a
/// submodule.  Depending on the "ignore" property of the submodule, some of
/// the flags may never be returned because they indicate changes that are
/// supposed to be ignored.
///
/// Submodule info is contained in 4 places: the HEAD tree, the index, config
/// files (both .git/config and .gitmodules), and the working directory.  Any
/// or all of those places might be missing information about the submodule
/// depending on what state the repo is in.  We consider all four places to
/// build the combination of status flags.
///
/// There are four values that are not really status, but give basic info
/// about what sources of submodule data are available.  These will be
/// returned even if ignore is set to "ALL".
///
/// * IN_HEAD   - superproject head contains submodule
/// * IN_INDEX  - superproject index contains submodule
/// * IN_CONFIG - superproject gitmodules has submodule
/// * IN_WD     - superproject workdir has submodule
///
/// The following values will be returned so long as ignore is not "ALL".
///
/// * INDEX_ADDED       - in index, not in head
/// * INDEX_DELETED     - in head, not in index
/// * INDEX_MODIFIED    - index and head don't match
/// * WD_UNINITIALIZED  - workdir contains empty directory
/// * WD_ADDED          - in workdir, not index
/// * WD_DELETED        - in index, not workdir
/// * WD_MODIFIED       - index and workdir head don't match
///
/// The following can only be returned if ignore is "NONE" or "UNTRACKED".
///
/// * WD_INDEX_MODIFIED - submodule workdir index is dirty
/// * WD_WD_MODIFIED    - submodule workdir has modified files
///
/// Lastly, the following will only be returned for ignore "NONE".
///
/// * WD_UNTRACKED      - wd contains untracked files
enum SubmoduleStatus {
  inHead(1),
  inIndex(2),
  inConfig(4),
  inWd(8),
  indexAdded(16),
  indexDeleted(32),
  indexModified(64),
  wdUninitialized(128),
  wdAdded(256),
  wdDeleted(512),
  wdModified(1024),
  wdIndexModified(2048),
  wdWdModified(4096),
  wdUntracked(8192);

  final int value;
  const SubmoduleStatus(this.value);

  static SubmoduleStatus fromValue(int value) => switch (value) {
    1 => inHead,
    2 => inIndex,
    4 => inConfig,
    8 => inWd,
    16 => indexAdded,
    32 => indexDeleted,
    64 => indexModified,
    128 => wdUninitialized,
    256 => wdAdded,
    512 => wdDeleted,
    1024 => wdModified,
    2048 => wdIndexModified,
    4096 => wdWdModified,
    8192 => wdUntracked,
    _ => throw ArgumentError('Unknown value for SubmoduleStatus: $value'),
  };
}

/// Submodule update values
///
/// These values represent settings for the `submodule.$name.update`
/// configuration value which says how to handle `git submodule update` for
/// this submodule.  The value is usually set in the ".gitmodules" file and
/// copied to ".git/config" when the submodule is initialized.
///
/// You can override this setting on a per-submodule basis with
/// `submodule_set_update()` and write the changed value to disk using
/// `submodule_save()`.  If you have overwritten the value, you can
/// revert it by passing `GIT_SUBMODULE_UPDATE_RESET` to the set function.
///
/// The values are:
///
/// - GIT_SUBMODULE_UPDATE_CHECKOUT: the default; when a submodule is
/// updated, checkout the new detached HEAD to the submodule directory.
/// - GIT_SUBMODULE_UPDATE_REBASE: update by rebasing the current checked
/// out branch onto the commit from the superproject.
/// - GIT_SUBMODULE_UPDATE_MERGE: update by merging the commit in the
/// superproject into the current checkout out branch of the submodule.
/// - GIT_SUBMODULE_UPDATE_NONE: do not update this submodule even when
/// the commit in the superproject is updated.
/// - GIT_SUBMODULE_UPDATE_DEFAULT: not used except as static initializer
/// when we don't want any particular update rule to be specified.
enum SubmoduleUpdate {
  checkout(1),
  rebase(2),
  merge(3),
  none(4),
  default$(0);

  final int value;
  const SubmoduleUpdate(this.value);

  static SubmoduleUpdate fromValue(int value) => switch (value) {
    1 => checkout,
    2 => rebase,
    3 => merge,
    4 => none,
    0 => default$,
    _ => throw ArgumentError('Unknown value for SubmoduleUpdate: $value'),
  };
}

/// Available tracing levels.  When tracing is set to a particular level,
/// callers will be provided tracing at the given level and all lower levels.
enum TraceLevel {
  /// No tracing will be performed.
  none(0),

  /// Severe errors that may impact the program's execution
  fatal(1),

  /// Errors that do not impact the program's execution
  error(2),

  /// Warnings that suggest abnormal data
  warn(3),

  /// Informational messages about program execution
  info(4),

  /// Detailed data that allows for debugging
  debug(5),

  /// Exceptionally detailed debugging data
  trace(6);

  final int value;
  const TraceLevel(this.value);

  static TraceLevel fromValue(int value) => switch (value) {
    0 => none,
    1 => fatal,
    2 => error,
    3 => warn,
    4 => info,
    5 => debug,
    6 => trace,
    _ => throw ArgumentError('Unknown value for TraceLevel: $value'),
  };
}

/// The kind of update to perform
enum TreeUpdateT {
  /// Update or insert an entry at the specified path
  upsert(0),

  /// Remove an entry from the specified path
  remove(1);

  final int value;
  const TreeUpdateT(this.value);

  static TreeUpdateT fromValue(int value) => switch (value) {
    0 => upsert,
    1 => remove,
    _ => throw ArgumentError('Unknown value for TreeUpdateT: $value'),
  };
}

/// Tree traversal modes
enum TreewalkMode {
  pre(0),
  post(1);

  final int value;
  const TreewalkMode(this.value);

  static TreewalkMode fromValue(int value) => switch (value) {
    0 => pre,
    1 => post,
    _ => throw ArgumentError('Unknown value for TreewalkMode: $value'),
  };
}

/// Flags which can be passed to worktree_prune to alter its
/// behavior.
enum WorktreePrune {
  valid(1),
  locked(2),
  workingTree(4);

  final int value;
  const WorktreePrune(this.value);

  static WorktreePrune fromValue(int value) => switch (value) {
    1 => valid,
    2 => locked,
    4 => workingTree,
    _ => throw ArgumentError('Unknown value for WorktreePrune: $value'),
  };
}
