// --- DO NOT EDIT MANUALLY ---
// This file contains hashes of libgit2 binaries downloaded by the build hook.
// For tests it is replaced with locally computed values; for releases the
// pre-release check enforces it is up-to-date.
//
// Generated by tool/generate_binary_hash.dart

// dart format off
// ignore_for_file: unnecessary_ignore, lines_longer_than_80_chars

/// The release tag used for downloading prebuilt binaries.
const releaseTag = 'ligit-v0.0.1';

/// SHA256 hashes for pre-built native binaries. Keys are the artifact
/// filenames. The map is empty in development; CI populates it before tagging.
const assetHashes = <String, String>{};
