// --- DO NOT EDIT MANUALLY ---
// This file contains hashes of libgit2 binaries downloaded by the build
// hook. For tests, it is replaced with actual assets built from the
// tarballs. For releases, a pre-release check asserts it's up-to-date.
//
// Generated by tool/generate_binary_hash.dart

// dart format off
// ignore_for_file: unnecessary_ignore, lines_longer_than_80_chars

/// The release tag used for downloading prebuilt binaries.
const releaseTag = 'ligit-v0.0.1';

/// SHA256 hashes for pre-built native binaries. Keys are the artifact
/// filenames.
const assetHashes = <String, String>{
  'libgit2-aarch64-ios-simulator.dylib': '71c87f6b0fab381f0c2e1fb3408f7cbcdafc68db744ffb7cb0ac2d27aae3eab6',
  'libgit2-aarch64-ios.dylib': '8faf85fc36b804110da1eb7b351f4d05521f8ed6227793a457dafb195075ba77',
  'libgit2-aarch64-linux-android.so': '409694456e3304c584ab32576f75671c72f6a7bcedeeb203cadd5d34380fd118',
  'libgit2-aarch64-linux.so': 'e67564df40ace5eb08db3cac4aa102cbe6dd03f889bc7adeec87e9627ec6c12d',
  'libgit2-aarch64-macos.dylib': 'a3133a6a9a64a83b968b5ea83c56d3337ae313eec84f5fe565180755c2ca0dd4',
  'libgit2-arm-linux-androideabi.so': 'e24c6af212ac52257f1a1a5200e381f0ceedd9e00c01a6002917a7214edcd5ea',
  'libgit2-x86_64-ios-simulator.dylib': 'f871db51dad23b0a7176dd66040d67a7e5c3f7fae51a4d349eb15a7ca170a2e4',
  'libgit2-x86_64-linux-android.so': 'b938c839378f5e5414b1f7bc53ffc41a979ccd47c0694fe91999d04a0b8c9a30',
  'libgit2-x86_64-linux.so': '50ddf398a4881463a114fbd4533f37c02f1afa395022b0d83b72d188a1691fb2',
  'libgit2-x86_64-macos.dylib': '7479bdc73c3de37ef3a4fd6a61395042cbcc129eff415572681226c43b015a6c',
  'libgit2-x86_64-windows.dll': '71617c32a421051a048133b2fc660fd808e456af54676fcb090d802b218f9a6b',
};
